### ISSUE TITLE
Shelley-testnet integration roadmap

### ISSUE THREAD

**Issue by ppershing** [vacuumlabs/adalite#544]
[sorry for Slovak, copy-pasted from internal notes]

This issue is meant to track our progress on shelley incentivized testnet. Keep updating with new relevant information (PR numbers, check done tasks, etc.)

# Git
- [x] treba dokoncit typescript PR, malo by byt v stave ze mozem kliknut merge ked sa vratim
  - ked sa dostane do toho stavu, vsetko ostatne sa uz moze rebasnut nad ten pr
- [ ] testnet brancha by mala dobehnut chybajuce commity z developu

# Backend info
- bude treba vyrobit testnet branchu na adalite-backend-service
- tam treba pofixovat db_api cally ak referencuju nejake zmigrovane tabulkove schemy

## Na backende potrebujeme radovo tieto cally

Normal view:
- [ ] `list_used_addresses(addrs)`
  - pre legacy adresy (cbor-encoded) sa pyta legacy tabulky, pre shelley sa pyta shelley tabulky    - note: pre legacy nestaci inferovat z list_transactions
- [ ] `transactions_for_addresses(addrs)`+legacy
  - neviem ci ako jeden call alebo separatne
  - je dost mozne ze legacy sa bude robit z nejakej genesis informacie, tazko povedat
  
Basic staking:  
- [ ] `account_info(pubkey_hex)`
  - +- to co vracia jormungandr (balance, counter, current staking, [total rewards])
  - bud je to priamo v databaze alebo proste nateraz robme proxy na jormungandr
- [ ] `staking_pools()`
  - zatial iba ziskavat list bud od jormun alebo z db
  - eventualne chceme zmergovat data z toho iohk registry repozitara
- [ ] `submit_tx()`

Staking history:
- [ ] `account_delegation_history(pubkey_hex)`

Hudba buducnosti?
- [ ] `account_transactions(pubkey_hex)` -> list transakcii na accounte
  - Budeme mat niekde v UI? Asi nie...
- [ ] `transactions_for_staking_key(pubkey_hex)`
  - listuje transakcie na group adresu
  - tunak mozeme zistit ze mame nieco na staking kluci ale nemame k tomu spending key. Bud sme zle spravili discovery alebo niekto spravil nieco divne a nam "deleguje" stake

  
# Frontend:

Basic staking
- [ ] treba zacat tahat account stav a ulozit si ho
  - zobrazit balance (a counter)
- [ ] simple stakovanie
  - treba si potahat zoznam validnych poolov od backendu
  - zadratovat UI a validovat moznosti
  - umoznit uzivatelovi vyrobit single-pool-staking transakciu
    - poslat ju na backend
    - neskor -- zratat fee a dialog

Current delegation  
- [ ] zobrazovanie aktualnej delegacie
  - zatial iba hashe a percenta
  - eventualne (ked budu backend data) aj nazvy+metadata o pooloch

Byron->shelley
- [ ] support for new addresses
  - internal representation
    - we need to keep both legacy and new addresses
    - m/44 vs m/1815 derivation paths should produce legacy vs new group addresses
  - adjust validation in send-money dialog
    - note: keep correct network (testnet) flag, reject mainnet
      
- [ ] legacy funds conversion
  - [bude sa tazko testovat + musime zistit ci to emurgo uz zvladlo v js-chain-libs]
  - imho netreba userov forcovat, staci ze nam bude fungovat legacy-utxo spending
    - na druhej strane, mozno by bolo fajn mat stav ze bud mas legacy a nemozes robit nic alebo nemas a robis veci normalne

Improved staking UI
- [ ] extended stakovanie
  - treba sa pozriet ako su na tom js-chain-libs
    - ci uz maju implementovane "NoStake" a "MultiStake"
    - ak ano, dostat do nasho wrapperu na budovanie transakcii
    - a potom v UI povolit prislusne varianty

Hudba buducnosti
- [ ] detekcia unstaked funds
  - [hudba buducnosti]
- [ ] zobrazovanie account historie
  - ked bude account_transactions na backende
  - treba potiahnut a zobrazit v UI
  - not sure if we want it as a feature

**Comment by PeterBenc** [comment]
Closing this since the issue is outdated.
